import path from "node:path";
import { configDefaults, defineConfig } from "vitest/config";

export default defineConfig({
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "src"),
    },
  },
  test: {
    environment: "node",
    exclude: [...configDefaults.exclude, ".next/**"],
    hookTimeout: 120000,
    testTimeout: 120000,
    coverage: {
      provider: "v8",
      include: [
        "src/app/page.tsx",
        "src/app/api/ingest/status/route.ts",
        "src/app/api/insights/digest/route.ts",
        "src/app/api/insights/movement/route.ts",
        "src/app/api/insights/today/route.ts",
        "src/app/api/insights/trends/route.ts",
        "src/app/api/live-lookups/enqueue/route.ts",
        "src/app/api/live-lookups/status/route.ts",
        "src/app/api/live-lookups/worker/route.ts",
        "src/app/api/notifications/channels/route.ts",
        "src/app/api/notifications/deliveries/route.ts",
        "src/app/api/notifications/dispatch/route.ts",
        "src/app/api/notifications/queue/route.ts",
        "src/app/api/notifications/refresh/route.ts",
        "src/app/api/notifications/rules/route.ts",
        "src/app/api/settings/status/route.ts",
        "src/app/api/watch-rules/route.ts",
        "src/components/dashboard/CatalogOpsDashboard.tsx",
        "src/instrumentation.ts",
        "src/lib/auth/admin.ts",
        "src/lib/auth/initial-admin.ts",
        "src/lib/auth/login-logo.ts",
        "src/lib/auth/schema.ts",
        "src/lib/auth/settings.ts",
        "src/lib/db/migrations.ts",
        "src/lib/db/startup-migrations.ts",
        "src/lib/demo/fixtures.ts",
        "src/lib/demo/repository.ts",
        "src/lib/email/adapter.ts",
        "src/lib/env.ts",
        "src/lib/ingest/gmail-query.ts",
        "src/lib/ingest/gmail-ingest-runner.ts",
        "src/lib/ingest/gmail.ts",
        "src/lib/ingest/google-auth.ts",
        "src/lib/ingest/juno-parser.ts",
        "src/lib/ingest/mail-source-test.ts",
        "src/lib/ingest/settings.ts",
        "src/lib/insights/normalize.ts",
        "src/lib/insights/movement.ts",
        "src/lib/insights/movement-repository.ts",
        "src/lib/insights/repository.ts",
        "src/lib/insights/trend-repository.ts",
        "src/lib/insights/watch-matcher.ts",
        "src/lib/juno-live/delay.ts",
        "src/lib/juno-live/lookup-runner.ts",
        "src/lib/juno-live/parser.ts",
        "src/lib/juno-live/settings.ts",
        "src/lib/juno-live/url.ts",
        "src/lib/logging/logger.ts",
        "src/lib/notifications/dispatcher.ts",
        "src/lib/notifications/matcher.ts",
        "src/lib/notifications/render.ts",
        "src/lib/notifications/repository.ts",
        "src/lib/notifications/script-options.ts",
        "src/lib/public-safety/check.ts",
        "src/lib/setup/status.ts",
        "src/lib/storage/attachment-storage.ts",
      ],
      reporter: ["text", "lcov"],
      thresholds: {
        statements: 100,
        branches: 100,
        functions: 100,
        lines: 100,
      },
    },
  },
});
