import type { MailAuthType, MailCredentialType, MailProvider } from "@/lib/ingest/mail-source";
import type { MailSourceConnectionTestResult } from "@/lib/ingest/mail-source-test";
import type { AttachmentStorageBackend } from "@/lib/storage/attachment-storage";
import type { SignalEventType, SignalSeverity } from "@/lib/insights/repository";
import type { NotificationChannelType } from "@/lib/notifications/types";
import type { SettingsGroupId } from "@/lib/settings/descriptors";

export type PatchValue = string | number | boolean | null;
export type DraftValues = Record<string, PatchValue>;
export type SsoProviderProtocol = "oidc" | "oauth2";
export type SsoProviderPreset = "custom_oidc" | "custom_oauth2" | "google_oidc" | "microsoft_entra_oidc" | "auth0_oidc" | "okta_oidc";
export type MailSourceDraft = {
  id?: string;
  name: string;
  provider: MailProvider;
  authType: MailAuthType;
  credentialType: MailCredentialType;
  credentialSecret: string;
  scopes: string;
  mailboxAddress: string;
  displayName: string;
  providerMailboxId: string;
  query: string;
  maxResults: number;
  lookbackMs: number;
  processedLabel: string;
  storageBackend: AttachmentStorageBackend;
  storageDir: string;
  storageEndpoint: string;
  storageBucket: string;
  storagePrefix: string;
  storageRegion: string;
  storageAccessKeyId: string;
  storageSecret: string;
  storageForcePathStyle: boolean;
  attachmentPattern: string;
  supplierCode: string;
  isActive: boolean;
};
export type MailSourceTestState = MailSourceConnectionTestResult | null;
export type SsoProviderDraft = {
  id?: string;
  providerId: string;
  displayName: string;
  protocol: SsoProviderProtocol;
  preset: SsoProviderPreset;
  buttonLabel: string;
  logoUrl: string;
  discoveryUrl: string;
  authorizationUrl: string;
  tokenUrl: string;
  userInfoUrl: string;
  clientId: string;
  clientSecret: string;
  scopes: string;
  enabled: boolean;
  sortOrder: number;
  adminEmailAllowlist: string;
  adminClaim: string;
  adminClaimValue: string;
};
export type NotificationChannelDraft = {
  id?: string;
  name: string;
  type: NotificationChannelType;
  enabled: boolean;
  webhookUrl: string;
  secretRef: string;
};
export type NotificationRuleDraft = {
  id?: string;
  name: string;
  channelId: string;
  enabled: boolean;
  signalTypes: SignalEventType[];
  severities: SignalSeverity[];
  minScore: number;
  includeWatchHits: boolean;
  includeDigest: boolean;
  cooldownMinutes: number;
};

export type SettingsTab = "overview" | SettingsGroupId;
