import { Archive, CircleCheck, Database, MailSearch } from "lucide-react";
import type { CatalogOpsDashboardProps } from "./CatalogOpsDashboard";

export const dashboardFixture: CatalogOpsDashboardProps = {
  stats: [
    { label: "Mailbox", value: "Configurable", detail: "mail source access", icon: MailSearch },
    { label: "Source", value: "Mail query", detail: "catalog mail search expression", icon: Archive },
    { label: "Deduping", value: "4 keys", detail: "message, RFC822, attachment, content", icon: CircleCheck },
    { label: "Storage", value: "raw XLSX", detail: "replayable attachment archive", icon: Database },
  ],
  pipeline: [
    {
      title: "Fetch",
      body: "Query active Gmail mail sources for Juno XLSX messages using configured mail source records.",
    },
    {
      title: "Normalize",
      body: "Extract source fields, pricing, stock, release dates, and deterministic hashes.",
    },
    {
      title: "Persist",
      body: "Store source mail, attachment hash, catalog snapshot, and raw item rows in Postgres.",
    },
    {
      title: "Live lookup",
      body: "Queue selected Juno IDs for read-only browser stock checks through a managed background process.",
    },
  ],
  commands: [
    "Open /settings",
    "pnpm gmail:smoke",
    "pnpm gmail:ingest",
    "pnpm gmail:ingest:write",
    "pnpm juno:live:enqueue",
    "pnpm juno:live:worker",
    "pnpm insights:refresh",
    "pnpm notifications:refresh",
  ],
  ingestState: {
    mailboxSourceId: "mail-source-gmail-workspace",
    mailboxAddress: "catalog@example.invalid",
    provider: "gmail",
    lastQuery: "has:attachment filename:xlsx newer_than:30d",
    lastQueryWindowFrom: "2026-06-16 00:00:00+00",
    lastQueryWindowTo: "2026-06-17 00:00:00+00",
    lastQueryStartedAt: "2026-06-17 01:00:00+00",
    lastQueryFinishedAt: "2026-06-17 01:00:07+00",
    lastQueryStatus: "succeeded",
    lastQueryError: null,
    lastQueryMessageCount: 2,
    lastQueryAttachmentCount: 1,
    lastSuccessfulMessageReceivedAt: "2026-06-17 01:00:00+00",
    lastIngestedSnapshotId: "4e02b7c8-ab7e-4305-b702-423a9287917f",
    lastIngestedCatalogDate: "2026-06-17",
    lastIngestedContentHash: "75fba5fd45de865441cf9d0899dc7a4f5f531a79fd4557c9d9b68f2f7b5d2a7a",
  },
  todaySignals: [
    {
      signalId: "signal-1",
      type: "watch_hit",
      severity: "watch",
      score: 15,
      title: "Watch hit: Lara Voss - Signal Path",
      detail: "Observed catalog row matched 1 watch rule(s).",
      createdAt: "2026-06-17 01:00:08+00",
      item: {
        identityId: "identity-1",
        junoId: "1148569-01",
        artist: "Lara Voss",
        title: "Signal Path",
        label: "Blue Note",
        catNo: "BN-101",
        genre: "Jazz",
        medium: "LP",
        stock: 2,
        dealerPriceGbp: "10.00",
        releaseDate: "2026-06-21",
      },
      reasons: ['Label exactly matches "Blue Note".'],
    },
    {
      signalId: "signal-2",
      type: "low_catalog_stock",
      severity: "warning",
      score: 2,
      title: "Low catalog stock: Lara Voss - Signal Path",
      detail: "Catalog stock field reports 2 units in the latest XLSX snapshot.",
      createdAt: "2026-06-17 01:00:09+00",
      item: {
        identityId: "identity-1",
        junoId: "1148569-01",
        artist: "Lara Voss",
        title: "Signal Path",
        label: "Blue Note",
        catNo: "BN-101",
        genre: "Jazz",
        medium: "LP",
        stock: 2,
        dealerPriceGbp: "10.00",
        releaseDate: "2026-06-21",
      },
      reasons: [],
    },
  ],
  movementSignals: [
    {
      signalId: "movement-1",
      type: "observed_stock_drop",
      severity: "warning",
      score: 60,
      title: "Observed stock change: Lara Voss - Signal Path",
      detail: "Observed live stock changed from 8 to 2.",
      createdAt: "2026-06-17 02:00:00+00",
      item: {
        identityId: "identity-1",
        junoId: "1148569-01",
        artist: "Lara Voss",
        title: "Signal Path",
        label: "Blue Note",
        catNo: "BN-101",
        genre: "Jazz",
        medium: "LP",
        stock: 2,
        dealerPriceGbp: "10.00",
        releaseDate: "2026-06-21",
      },
      reasons: ['Label exactly matches "Blue Note".'],
    },
    {
      signalId: "movement-2",
      type: "fast_mover_candidate",
      severity: "watch",
      score: 90,
      title: "Fast mover candidate: Lara Voss - Signal Path",
      detail: "Fast mover candidate: observed live stock changed from 8 to 2 within 18 hours. This is a proxy candidate based only on observed stock changes.",
      createdAt: "2026-06-17 02:01:00+00",
      item: {
        identityId: "identity-1",
        junoId: "1148569-01",
        artist: "Lara Voss",
        title: "Signal Path",
        label: "Blue Note",
        catNo: "BN-101",
        genre: "Jazz",
        medium: "LP",
        stock: 2,
        dealerPriceGbp: "10.00",
        releaseDate: "2026-06-21",
      },
      reasons: [],
    },
  ],
  catalogTrends: {
    window: {
      currentFrom: "2026-06-11T00:00:00.000Z",
      currentTo: "2026-06-18T00:00:00.000Z",
      previousFrom: "2026-06-04T00:00:00.000Z",
      previousTo: "2026-06-11T00:00:00.000Z",
    },
    genres: [
      {
        key: "jazz",
        label: "Jazz",
        currentCount: 9,
        previousCount: 3,
        delta: 6,
        percentChange: 200,
        watchHitCount: 2,
      },
      {
        key: "house",
        label: "House",
        currentCount: 0,
        previousCount: 1,
        delta: -1,
        percentChange: -100,
        watchHitCount: 0,
      },
    ],
    labels: [
      {
        key: "blue note",
        label: "Blue Note",
        currentCount: 7,
        previousCount: 2,
        delta: 5,
        percentChange: 250,
        watchHitCount: 2,
      },
    ],
    watchOverlap: [
      {
        key: "label:blue note",
        label: "Label: Blue Note",
        currentCount: 2,
        previousCount: 1,
        delta: 1,
        percentChange: 100,
        watchHitCount: 2,
      },
    ],
  },
  operatorDigest: {
    generatedAt: "2026-06-17 02:02:00+00",
    counts: {
      watchHitsToday: 1,
      lowCatalogStockToday: 1,
      lowLiveStockToday: 1,
      restocksToday: 1,
      fastMoverCandidatesToday: 1,
    },
    topSignals: [],
    topGenres: [
      {
        key: "jazz",
        label: "Jazz",
        currentCount: 9,
        previousCount: 3,
        delta: 6,
        percentChange: 200,
        watchHitCount: 2,
      },
    ],
    topLabels: [
      {
        key: "blue note",
        label: "Blue Note",
        currentCount: 7,
        previousCount: 2,
        delta: 5,
        percentChange: 250,
        watchHitCount: 2,
      },
    ],
  },
  dashboardSavedViews: [
    {
      id: "dashboard-view-1",
      name: "Watch hits",
      filters: {
        signalTypes: ["watch_hit"],
        severities: [],
        watchHitsOnly: true,
        lowStockOnly: false,
        movementOnly: false,
        dateRange: "all",
      },
      sortOrder: 0,
      createdAt: "2026-06-17 02:10:00+00",
      updatedAt: "2026-06-17 02:10:00+00",
    },
    {
      id: "dashboard-view-2",
      name: "Low stock review",
      filters: {
        signalTypes: [],
        severities: ["warning", "critical"],
        watchHitsOnly: false,
        lowStockOnly: true,
        movementOnly: false,
        dateRange: "7d",
      },
      sortOrder: 1,
      createdAt: "2026-06-17 02:11:00+00",
      updatedAt: "2026-06-17 02:11:00+00",
    },
  ],
  watchRules: [
    {
      id: "watch-rule-1",
      type: "label",
      pattern: "Blue Note",
      patternNorm: "blue note",
      weight: 15,
      enabled: true,
      createdAt: "2026-06-17 00:30:00+00",
      updatedAt: "2026-06-17 00:30:00+00",
    },
    {
      id: "watch-rule-2",
      type: "exclude_keyword",
      pattern: "damaged sleeve",
      patternNorm: "damaged sleeve",
      weight: -20,
      enabled: false,
      createdAt: "2026-06-17 00:35:00+00",
      updatedAt: "2026-06-17 00:35:00+00",
    },
  ],
  notificationDeliveries: [
    {
      id: "delivery-1",
      ruleId: "notification-rule-1",
      ruleName: "Watch and movement alerts",
      channelId: "notification-channel-1",
      channelName: "In-app notifications",
      channelType: "in_app",
      signalEventId: "signal-1",
      digestKey: null,
      status: "queued",
      deliveryKey: "signal:notification-rule-1:notification-channel-1:signal-1",
      subject: "[Watch hit] Lara Voss - Signal Path",
      body: "Read-only signal from Juno Wholesale Ops.",
      payload: { source: "juno-wholesale-ops", readOnly: true },
      attempts: 0,
      lastError: null,
      queuedAt: "2026-06-17 02:05:00+00",
      sentAt: null,
      updatedAt: "2026-06-17 02:05:00+00",
      signalType: "watch_hit",
      severity: "watch",
      score: 15,
    },
    {
      id: "delivery-2",
      ruleId: "notification-rule-2",
      ruleName: "Daily operator digest",
      channelId: "notification-channel-2",
      channelName: "Ops webhook",
      channelType: "webhook",
      signalEventId: null,
      digestKey: "2026-06-17",
      status: "sent",
      deliveryKey: "digest:notification-rule-2:notification-channel-2:2026-06-17",
      subject: "[Operator digest] 2026-06-17",
      body: "Read-only operator digest from Juno Wholesale Ops.",
      payload: { source: "juno-wholesale-ops", readOnly: true },
      attempts: 1,
      lastError: null,
      queuedAt: "2026-06-17 02:06:00+00",
      sentAt: "2026-06-17 02:07:00+00",
      updatedAt: "2026-06-17 02:07:00+00",
      signalType: null,
      severity: null,
      score: null,
    },
  ],
  notificationRules: [
    {
      id: "notification-rule-1",
      name: "Watch and movement alerts",
      channelId: "notification-channel-1",
      channelName: "In-app notifications",
      channelType: "in_app",
      channelEnabled: true,
      enabled: true,
      signalTypes: ["watch_hit", "observed_stock_drop", "observed_live_low_stock"],
      severities: ["watch", "warning"],
      minScore: 1,
      includeWatchHits: true,
      includeDigest: false,
      cooldownMinutes: 60,
      createdAt: "2026-06-17 02:00:00+00",
      updatedAt: "2026-06-17 02:00:00+00",
    },
    {
      id: "notification-rule-2",
      name: "Daily operator digest",
      channelId: "notification-channel-2",
      channelName: "Ops webhook",
      channelType: "webhook",
      channelEnabled: true,
      enabled: true,
      signalTypes: [],
      severities: [],
      minScore: 0,
      includeWatchHits: true,
      includeDigest: true,
      cooldownMinutes: 1440,
      createdAt: "2026-06-17 02:01:00+00",
      updatedAt: "2026-06-17 02:01:00+00",
    },
  ],
  notificationChannels: [
    {
      id: "notification-channel-1",
      name: "In-app notifications",
      type: "in_app",
      enabled: true,
      config: {},
      secretRef: null,
      configSummary: "Dashboard-only read-only alerts",
      createdAt: "2026-06-17 02:00:00+00",
      updatedAt: "2026-06-17 02:00:00+00",
    },
    {
      id: "notification-channel-2",
      name: "Ops webhook",
      type: "webhook",
      enabled: true,
      config: { url: "[configured]" },
      secretRef: "JUNO_OPS_WEBHOOK_URL",
      configSummary: "Webhook URL from JUNO_OPS_WEBHOOK_URL",
      createdAt: "2026-06-17 02:01:00+00",
      updatedAt: "2026-06-17 02:01:00+00",
    },
  ],
  setupStatus: {
    ready: false,
    steps: [
      {
        id: "database",
        label: "Database",
        state: "complete",
        detail: "required for persistence and worker state",
        action: null,
        missing: [],
        settings: [
          {
            key: "DATABASE_URL",
            label: "Postgres connection",
            source: "runtime",
            state: "configured",
            value: "configured",
            secret: true,
          },
        ],
        guardrails: [
          {
            label: "Migration ledger",
            state: "ok",
            detail: "Next.js startup applied migrations and saved settings are available.",
          },
        ],
      },
      {
        id: "mail",
        label: "Mail sources",
        state: "missing",
        detail: "required for catalog email ingestion",
        action: "Create an active mail source with a read-only adapter and verified credential.",
        missing: ["mail_source"],
        settings: [
          {
            key: "active_mail_sources",
            label: "Active sources",
            source: "database",
            state: "configured",
            value: "0",
          },
        ],
        guardrails: [
          {
            label: "Cursored mail search",
            state: "ok",
            detail: "Ingest uses mailbox source cursor state and content hashes to avoid duplicate sheets.",
          },
        ],
      },
      {
        id: "juno",
        label: "Live stock lookup",
        state: "missing",
        detail: "required for browser-based stock checks",
        action: "Configure credentials and keep delay bounds sane before starting the worker.",
        missing: ["juno_login_email", "juno_login_password"],
        settings: [
          {
            key: "juno_login_email",
            label: "Login email",
            source: "unset",
            state: "missing",
            value: "not set",
          },
          {
            key: "juno_live_poll_interval_ms",
            label: "Automatic lookup interval",
            source: "unset",
            state: "disabled",
            value: "manual only",
          },
        ],
        guardrails: [
          {
            label: "Scheduled polling",
            state: "warning",
            detail: "No polling interval is set; lookups stay manual.",
          },
        ],
      },
      {
        id: "auth",
        label: "Admin auth",
        state: "warning",
        detail: "Better Auth admin gate is always enabled",
        action: "Create an admin user or configure an external provider admin allowlist.",
        missing: [],
        settings: [
          {
            key: "auth_base_url",
            label: "Site address",
            source: "runtime",
            state: "configured",
            value: "https://inventory-dev.example.test",
          },
        ],
        guardrails: [
          {
            label: "Admin bootstrap",
            state: "warning",
            detail: "Admin user count is not available yet.",
          },
        ],
      },
    ],
  },
};
